CREATE DATABASE test;
USE test;

DROP TABLE part;
CREATE TABLE part (
	P_PARTKEY		INT,
	P_NAME			VARCHAR,
	P_MFGR			VARCHAR,
	P_BRAND			VARCHAR,
	P_TYPE			VARCHAR,
	P_SIZE			INT,
	P_CONTAINER		VARCHAR,
	P_RETAILPRICE	FLOAT,
	P_COMMENT		VARCHAR,
	PRIMARY KEY (P_PARTKEY)
);
	
DROP TABLE region;
CREATE TABLE region (
	R_REGIONKEY		INT,
	R_NAME		 	VARCHAR,
	R_COMMENT		VARCHAR,
	PRIMARY KEY (R_REGIONKEY)
);

DROP TABLE nation;
CREATE TABLE nation (
	N_NATIONKEY		INT,
	N_NAME			VARCHAR,
	N_REGIONKEY		INT NOT NULL,
	N_COMMENT		VARCHAR,
	PRIMARY KEY (N_NATIONKEY)
);

DROP TABLE supplier;
CREATE TABLE supplier (
	S_SUPPKEY		INT,
	S_NAME			VARCHAR,
	S_addRESS		VARCHAR,
	S_NATIONKEY		INT NOT NULL,
	S_PHONE			VARCHAR,
	S_ACCTBAL		FLOAT,
	S_COMMENT		VARCHAR,
	PRIMARY KEY (S_SUPPKEY)
);

DROP TABLE customer;
CREATE TABLE customer (
	C_CUSTKEY		INT,
	C_NAME			VARCHAR,
	C_addRESS		VARCHAR,
	C_NATIONKEY		INT NOT NULL,
	C_PHONE			VARCHAR,
	C_ACCTBAL		FLOAT,
	C_MKTSEGMENT	VARCHAR,
	C_COMMENT		VARCHAR,
	PRIMARY KEY (C_CUSTKEY)
);

DROP TABLE partsupp;
CREATE TABLE partsupp (
	PS_PARTKEY		INT NOT NULL,
	PS_SUPPKEY		INT NOT NULL,
	PS_AVAILQTY		INT,
	PS_SUPPLYCOST	FLOAT,
	PS_COMMENT		VARCHAR
);
ALTER TABLE partsupp ADD CONSTRAINT PK_NAME PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY);

DROP TABLE orders;
CREATE TABLE orders (
	O_ORDERKEY		INT,
	O_CUSTKEY		INT NOT NULL,
	O_ORDERSTATUS	VARCHAR,
	O_TOTALPRICE	FLOAT,
	O_ORDERDATE		DATE,
	O_ORDERPRIORITY	VARCHAR,
	O_CLERK			VARCHAR,
	O_SHIPPRIORITY	INT,
	O_COMMENT		VARCHAR,
	PRIMARY KEY (O_ORDERKEY)
);

DROP TABLE lineitem;
CREATE TABLE lineitem (
	L_ORDERKEY		INT NOT NULL,
	L_PARTKEY		INT NOT NULL,
	L_SUPPKEY		INT NOT NULL,
	L_LINENUMBER	INT,
	L_QUANTITY		FLOAT,
	L_EXTENDEDPRICE	FLOAT,
	L_DISCOUNT		FLOAT,
	L_TAX			FLOAT,
	L_RETURNFLAG	VARCHAR,
	L_LINESTATUS	VARCHAR,
	L_SHIPDATE		DATE,
	L_COMMITDATE	DATE,
	L_RECEIPTDATE	DATE,
	L_SHIPINSTRUCT	VARCHAR,
	L_SHIPMODE		VARCHAR,
	L_COMMENT		VARCHAR
);
ALTER TABLE lineitem ADD CONSTRAINT PK_NAME PRIMARY KEY  (L_ORDERKEY, L_LINENUMBER);

ALTER TABLE supplier ADD CONSTRAINT FK_NAME FOREIGN KEY  (S_NATIONKEY) REFERENCES nation(N_NATIONKEY);
ALTER TABLE partsupp ADD CONSTRAINT FK_NAME_1 FOREIGN KEY  (PS_PARTKEY) REFERENCES part(P_PARTKEY);
ALTER TABLE partsupp ADD CONSTRAINT FK_NAME_2 FOREIGN KEY  (PS_SUPPKEY) REFERENCES supplier(S_SUPPKEY);
ALTER TABLE customer ADD CONSTRAINT FK_NAME FOREIGN KEY  (C_NATIONKEY) REFERENCES nation(N_NATIONKEY);
ALTER TABLE orders ADD CONSTRAINT FK_NAME FOREIGN KEY  (O_CUSTKEY) REFERENCES customer(C_CUSTKEY);
ALTER TABLE lineitem  ADD CONSTRAINT FK_NAME_1 FOREIGN KEY  (L_ORDERKEY) REFERENCES orders(O_ORDERKEY);
ALTER TABLE lineitem  ADD CONSTRAINT FK_NAME_2 FOREIGN KEY  (L_PARTKEY,L_SUPPKEY) REFERENCES partsupp(PS_PARTKEY,PS_SUPPKEY);
ALTER TABLE nation ADD CONSTRAINT FK_NAME FOREIGN KEY  (N_REGIONKEY) REFERENCES region(R_REGIONKEY);

DESC part;
DESC region;
DESC nation;
DESC supplier;
DESC customer;
DESC partsupp;
DESC orders;
DESC lineitem;
