CREATE DATABASE test;
USE test;

DROP TABLE nation;
CREATE TABLE nation (
	N_NATIONKEY		INT,
	N_NAME			VARCHAR,
	N_REGIONKEY		INT NOT NULL,
	N_COMMENT		VARCHAR,
	PRIMARY KEY (N_NATIONKEY)
);

DROP TABLE supplier;
CREATE TABLE supplier (
	S_SUPPKEY		INT,
	S_NAME			VARCHAR,
	S_addRESS		VARCHAR,
	S_NATIONKEY		INT NOT NULL,
	PRIMARY KEY (S_SUPPKEY)
);

ALTER TABLE supplier ADD CONSTRAINT FK_NAME FOREIGN KEY  (S_NATIONKEY) REFERENCES nation(N_NATIONKEY);
INSERT INTO nation VALUES (0,'a', 0,'a'),(1,'a', 0,'a'),(2,'a', 0,'a'),(3,'a', 0,'a');
INSERT INTO supplier VALUES (0,'a','b',4);
SELECT * FROM supplier;


ALTER TABLE supplier  DROP FOREIGN KEY FUCK_NAME;
INSERT INTO supplier VALUES (0,'a','b',4);
SELECT * FROM supplier;

ALTER TABLE supplier  DROP FOREIGN KEY FK_NAME;
INSERT INTO supplier VALUES (0,'a','b',4);
SELECT * FROM supplier;
