USE test;
SHOW TABLES;
DESC region;

INSERT INTO region VALUES (4, 'CAN', 'COMMENT');
SELECT * FROM region WHERE R_REGIONKEY = 4;

DELETE FROM region WHERE R_NAME = 'CAN';
SELECT * FROM region WHERE R_REGIONKEY = 4;

SELECT * FROM region WHERE R_NAME = 'FUCK';
UPDATE region SET R_NAME = 'FUCK' WHERE R_REGIONKEY = 3;
SELECT * FROM region WHERE R_NAME = 'FUCK';
UPDATE region SET R_NAME = 'EUROPE                   ' WHERE R_REGIONKEY = 3;
SELECT * FROM region WHERE R_NAME = 'FUCK';

ALTER TABLE region ADD R_FUCK INT;
DESC region;
ALTER TABLE region DROP R_FUCK;
