USE db_fk;

CREATE TABLE AA(
	IDA INT NOT NULL,
	NAMEA VARCHAR NOT NULL,
	PRIMARY KEY (IDA)
);

CREATE TABLE BB(
	IDB INT NOT NULL,
	NAMEB VARCHAR NOT NULL,
	PRIMARY KEY (IDB)
);

CREATE INDEX IDX1 ON AA (NAMEA);
CREATE INDEX IDX2 ON BB (NAMEB);

ALTER TABLE BB ADD CONSTRAINT FK1 FOREIGN KEY (IDB) REFERENCES AA (IDA);
DESC BB;

ALTER TABLE BB DROP FOREIGN KEY FK1;
DESC BB;

ALTER TABLE BB ADD CONSTRAINT FK2 FOREIGN KEY (IDB, NAMEB) REFERENCES AA (IDA, NAMEA);
DESC BB;
INSERT INTO AA VALUES (0, 'A');
INSERT INTO BB VALUES (0, 'B');
INSERT INTO BB VALUES (0, 'A');