#include <vector>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <queue>
#include <math.h>
#include <cmath>
#include <assert.h>
#include <map>

using std::cout;
using std::endl;
using std::cin;
using std::vector;
using std::string;
using std::ostringstream;
using std::ifstream;
using std::ofstream;
using std::ios;
using std::queue;
using std::ceil;
using std::map;
